//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-322 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.12 at 10:22:19 AM CEST 
//


package com.tecmaral.domain.user;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tecmaral.domain.user package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DatosAdicionales_QNAME = new QName("user.tecmaral.es", "DatosAdicionales");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tecmaral.domain.user
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DatosIdentificacion }
     * 
     */
    public DatosIdentificacion createDatosIdentificacion() {
        return new DatosIdentificacion();
    }

    /**
     * Create an instance of {@link DatosAdicionalesType }
     * 
     */
    public DatosAdicionalesType createDatosAdicionalesType() {
        return new DatosAdicionalesType();
    }

    /**
     * Create an instance of {@link Usuario }
     * 
     */
    public Usuario createUsuario() {
        return new Usuario();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DatosAdicionalesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "user.tecmaral.es", name = "DatosAdicionales")
    public JAXBElement<DatosAdicionalesType> createDatosAdicionales(DatosAdicionalesType value) {
        return new JAXBElement<DatosAdicionalesType>(_DatosAdicionales_QNAME, DatosAdicionalesType.class, null, value);
    }

}
