//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-322 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.12 at 10:22:19 AM CEST 
//


package com.tecmaral.domain.user;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.tecmaral.domain.user.comun.datoscontacto.DatosContacto;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DatosIdentificacion" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TipoIdentific" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DatosContacto" type="{datoscontacto.tecmaral.es}DatosContacto" minOccurs="0"/>
 *         &lt;element ref="{user.tecmaral.es}DatosAdicionales"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datosIdentificacion",
    "datosContacto",
    "datosAdicionales"
})
@XmlRootElement(name = "Usuario", namespace = "user.tecmaral.es")
public class Usuario
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "DatosIdentificacion", namespace = "user.tecmaral.es")
    protected DatosIdentificacion datosIdentificacion;
    @XmlElement(name = "DatosContacto", namespace = "user.tecmaral.es")
    protected DatosContacto datosContacto;
    @XmlElement(name = "DatosAdicionales", namespace = "user.tecmaral.es", required = true)
    protected DatosAdicionalesType datosAdicionales;

    /**
     * Gets the value of the datosIdentificacion property.
     * 
     * @return
     *     possible object is
     *     {@link DatosIdentificacion }
     *     
     */
    public DatosIdentificacion getDatosIdentificacion() {
        return datosIdentificacion;
    }

    /**
     * Sets the value of the datosIdentificacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosIdentificacion }
     *     
     */
    public void setDatosIdentificacion(DatosIdentificacion value) {
        this.datosIdentificacion = value;
    }

    /**
     * Gets the value of the datosContacto property.
     * 
     * @return
     *     possible object is
     *     {@link DatosContacto }
     *     
     */
    public DatosContacto getDatosContacto() {
        return datosContacto;
    }

    /**
     * Sets the value of the datosContacto property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosContacto }
     *     
     */
    public void setDatosContacto(DatosContacto value) {
        this.datosContacto = value;
    }

    /**
     * Gets the value of the datosAdicionales property.
     * 
     * @return
     *     possible object is
     *     {@link DatosAdicionalesType }
     *     
     */
    public DatosAdicionalesType getDatosAdicionales() {
        return datosAdicionales;
    }

    /**
     * Sets the value of the datosAdicionales property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosAdicionalesType }
     *     
     */
    public void setDatosAdicionales(DatosAdicionalesType value) {
        this.datosAdicionales = value;
    }

}
