//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-322 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.12 at 10:22:19 AM CEST 
//


package com.tecmaral.domain.user.comun.datoscontacto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tecmaral.domain.user.comun.datoscontacto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tecmaral.domain.user.comun.datoscontacto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DatosContacto }
     * 
     */
    public DatosContacto createDatosContacto() {
        return new DatosContacto();
    }

    /**
     * Create an instance of {@link DatosAdicionalesContacto }
     * 
     */
    public DatosAdicionalesContacto createDatosAdicionalesContacto() {
        return new DatosAdicionalesContacto();
    }

}
